all: basic-2-lines   2-lines-one-lacks-morphemes

basic-2-lines:
	~/anaconda/bin/python3 ~/github/yamlToEAF/toEAF.py bearAndAnt-2-complete-lines.yaml

2-lines-one-lacks-morphemes:
	~/anaconda/bin/python3 ~/github/yamlToEAF/toEAF.py bearAndAnt-2-lines-1-lacks-morphemes.yaml


